### ISSUE TITLE
Move files from one location to another

### ISSUE THREAD

**Issue by gabepm100** [WhitmanCS370/OGGS_repo#27]
Be able to specify using the cli that you are moving a file from one location to another.

Example Call:
python3 Interface.py -mv /home/gabe/Documents/coffee.wav /home/gabe/Documents/Design

**Comment by ggrgg13** [comment]
The one use case I can think of is importing audio files.

**Comment by ggrgg13** [comment]
Deemed unnecessary. Importing file is already implemented.
