### ISSUE TITLE
Create new folder/playlist

### ISSUE THREAD

**Issue by gabepm100** [WhitmanCS370/OGGS_repo#29]
Be able to specify the location of a folder and then create a new folder in that location

Example command: 
"python interface.py -nfld NewFolderName /New/Folder/Location

**Comment by ggrgg13** [comment]
I think playlist should not be folder based but rather purely database driven. As in, if I create a playlist, it creates a new table containing references to files, but the files added to a playlist don't change place at all.

**Comment by ObaltzerS** [comment]
this is possible using the current CLI, using the new_playlist and playlist_add commands
